### ISSUE TITLE
Sending messages to autopilot

### ISSUE THREAD

**Issue by Sirius215** [asv-soft/asv-mavlink#35]
Hello, my name is Pavel, I'm new to C#, I'm working on a module for sending a Mavlink message rc_channels_override to autopilot. Do you have an example of sending messages to autopilot?

**Comment by asv-soft-u01** [comment]
Hello Pavel! You can send a Mavlink message using an example below:
`public class MavlinkConnectionTest
{
    public MavlinkConnectionTest()
    { 
        // Create a link between your app and autopilot. Check connection string on autopilot and adjust accordingly,
        // this is just an example
        
        // for TCP client connection:               tcp://127.0.0.1:9002
        // for TCP server(listen) connection:       tcp://127.0.0.1:9002?srv=true
        // for UDP connection:                      udp://127.0.0.1:1234?rhost=127.0.0.1&rport=1235
        // for COM\serial port connection Linux:    serial:/dev/ttyACM0?br=115200
        // for COM\serial port connection Windows:  serial:COM4?br=115200
        var connection = MavlinkV2Connection.Create("tcp://127.0.0.1:9002?srv=true");
        
        // create a packet to send over your connection
        var packet = new RcChannelsOverridePacket()
        {
            SystemId = 1, // this is message sender SystemId
            ComponentId = 1, // this is message sender ComponentId
            Payload =
            {
                TargetComponent = 1, // this is your target autopilot component Id
                TargetSystem = 1, // this is your target autopilot system Id
                // below are payload params that need to be filled out according to what you want your message to do
                // see Mavlink documentation on the matter https://mavlink.io/en/messages/common.html look for RC_CHANNELS_OVERRIDE
                Chan1Raw = 0,
                Chan2Raw = 0,
                Chan3Raw = 0,
                Chan5Raw = 0,
                Chan6Raw = 0,
                Chan7Raw = 0,
                Chan8Raw = 0,
                Chan9Raw = 0,
                Chan10Raw = 0,
                Chan11Raw = 0,
                Chan12Raw = 0,
                Chan13Raw = 0,
                Chan14Raw = 0,
                Chan15Raw = 0,
                Chan16Raw = 0,
                Chan17Raw = 0,
                Chan18Raw = 0,
            }
        };
        
        // send packet with your message
        connection.Send(packet, CancellationToken.None);
    }`

If you still have questions on the matter i will be happy to help!

**Comment by Sirius215** [comment]
Thank you very much, it works great!

**Comment by asv-soft-u01** [comment]
Happy to help!)
