### ISSUE TITLE
Reading messege from autopilot

### ISSUE THREAD

**Issue by Sirius215** [asv-soft/asv-mavlink#38]
Hello, could you give an example of how to read a message from autopilot. I need the GIMBAL_DEVICE_ATTITUDE_STATUS message. In python, I did it using recv_match(), is there something like that here?
![GimbalStatus](https://github.com/asv-soft/asv-mavlink/assets/116075933/98e79b11-45e0-47e6-9809-30bb2fe2c2f0)

**Comment by fhgrderungs** [comment]
A simple approach for subscribing to all messages and filter by specific message:

```csharp
var connection = new MavlinkV2Connection("udp://0.0.0.0:14540", p =>
{
    MavlinkV2Connection.RegisterDefaultDialects(p);    
});

connection.Subscribe(packet =>
{
    if(packet is GimbalControlPacket gimbalControlPacket)
    {
        Console.WriteLine(gimbalControlPacket.Payload.DemandedRateX);
    }
});
```

if you just want a specific message (example GimbalControlPacket) change to:

```csharp
connection.OfType<GimbalControlPacket>().Subscribe(packet =>
{
    Console.WriteLine(packet.Payload.DemandedRateX);
});
```

Unfortunately I dont see the mssage `GIMBAL_DEVICE_ATTITUDE_STATUS` in the code. Maybe @asvol can help here.

**Comment by Sirius215** [comment]
Thanks! I didn't find this message either.

**Comment by asvol** [comment]
0. You can use the method described above.
1. Or you can use a console application. Example: Asv.Mavlink.Shell.exe mavlink --cs=tcp://127.0.0.1:5760
2. Or use our open GUI program [here](https://github.com/asv-soft/asv-drones). But it is still under development.

Yes. Messages GIMBAL_* not present now. Maybe these are new messages in Mavlink. I can add them if needed.



![image](https://github.com/asv-soft/asv-mavlink/assets/1770739/c44d1653-3835-4526-9e4c-ae5aa2d55e22)
![image](https://github.com/asv-soft/asv-mavlink/assets/1770739/cbe231f5-61dc-4395-a40a-edb78cfee249)

**Comment by Sirius215** [comment]
Thank you very much!
