### ISSUE TITLE
PARAM_EXT

### ISSUE THREAD

**Issue by matveylapin** [asv-soft/asv-mavlink#47]
Very cool project! Please tell me, do you plan to support the PARAM_EXT microservice? I am developing my own firmware and would really like to use this type of parameters, but I have not found a ground station with support.

**Comment by asv-soft-u02** [comment]
Hello there! Glad to see that you are interested in our project! Could you please describe in detail your issue or suggestion?

> Very cool project! Please tell me, do you plan to support the PARAM_EXT microservice? I am developing my own firmware and would really like to use this type of parameters, but I have not found a ground station with support.

**Comment by asv-soft-u02** [comment]
Yes, that's true. We are planning to add extended params microservice as soon as possible. Stay tuned :D
