### ISSUE TITLE
Unable to find packages Asv.Cfg, Asv.Common, and Asv.IO

### ISSUE THREAD

**Issue by teklot** [asv-soft/asv-mavlink#83]
This project (v3.10.4) is referencing nonexistent Asv.Cfg, Asv.Common, and Asv.IO v3.0.0-dev.4 packages. Thanks!

**Comment by asv-soft-u05** [comment]
Hello! This version of project is still in development that is why it is referencing dev packages. We use night build and private nuget server that is why you can't get this versions of packages. 
Stay tuned. We'll be releasing new version of Asv.Common for public use very soon.

**Comment by teklot** [comment]
Thanks for the update! I appreciate all your efforts and great work.
